## NUMPY

In [2]:
import numpy as np
arr=np.array(
    [123]
)
print(arr)
print(arr.ndim)

[123]
1


In [3]:
import numpy as np
arr=np.array([[
    [1,2,3],[2,3,4]
],
[
    [2,3,5],[5,6,7]
    ]])
# print(arr)
print(arr.ndim)
print(arr[0,0,1])
print(arr[1,0,2])

3
2
5


In [4]:
import numpy as np
n=np.array([1,2,3])
m=np.array([1,2,3])
print(n+m)
print(n-m)
print(n*m)
print(n/m)
print(n**m)
print(n%m)
print(n//m)
print("-"*22)
if n is m:
    print('they are in same memory')
else:
    print('they are in different memory')

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
[ 1  4 27]
[0 0 0]
[1 1 1]
----------------------
they are in different memory


numpy Attributes

In [ ]:
s=np.array([1,2,3,4,5,6])
s
s.ndim

1

In [13]:
s.shape

(6,)

In [14]:
s.size

6

In [15]:
s.itemsize

8

In [16]:
s.dtype

dtype('int64')

ASTYPE -----> is used change the datatype

In [20]:
s.astype(float)
s.astype(str)

array(['1', '2', '3', '4', '5', '6'], dtype='<U21')

In [22]:
#1 dim array
d=np.array([1,2,3,4,5,6])
d
d.ndim

1

In [24]:
d=np.array([
    [1,2,3,4,5,6]
    ])
d.ndim

2

In [27]:
d=np.array(
    [
        [
            [1,2,3,4,5,6],
            [1,2,3,4,5,6],
            [1,2,3,4,5,6]

        ],[
            [1,2,3,4,5,6],
            [1,2,3,4,5,6],
            [1,2,3,4,5,6]

        ],[
            [1,2,3,4,5,6],
            [1,2,3,4,5,6],
            [1,2,3,4,5,6]

        ]
    ])
d.ndim

3

In [ ]:
d=np.array(
    [[
        [
            [1,2,3,4,5,6],
            [1,2,3,4,5,6],
            [1,2,3,4,5,6]

        ],[
            [1,2,3,4,5,6],
            [1,2,3,4,5,6],
            [1,2,3,4,5,6]

        ]
    ],[
        [
            [1,2,3,4,5,6],
            [1,2,3,4,5,6],
            [1,2,3,4,5,6]

        ],[
            [1,2,3,4,5,6],
            [1,2,3,4,5,6],
            [1,2,3,4,5,6]

        ]
    ]
    ]
    )
d.ndim

4

METHODS

In [30]:
s

array([1, 2, 3, 4, 5, 6])

In [34]:
m=np.arange(1,11)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one=np.ones([5,2,5],dtype=int)
one

In [ ]:
z=np.zeros([5,2,5],dtype=int)
z

In [ ]:
f=np.full([3,5,6],6)
f

In [ ]:
a=np.eye(5,5,dtype=int)
a


In [56]:
b=np.linspace(10,200,10)
b

array([ 10.        ,  31.11111111,  52.22222222,  73.33333333,
        94.44444444, 115.55555556, 136.66666667, 157.77777778,
       178.88888889, 200.        ])

In [ ]:
n=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
n.reshape(6,2)

In [73]:
n.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

OPERATORS

In [ ]:
# Arthimatic operations
#-----------------------------
arr=np.array([1,2,3])
arr+5
arr-5
arr*2
arr/3
arr//6
arr%6
arr**2

arr1=np.array([3,4,5])
np.add(arr,arr1)
np.subtract(arr,arr1)
np.multiply(arr,arr1)
np.divide(arr,arr1)
np.floor_divide(arr,arr1)
np.mod(arr,arr1)
np.power(arr,arr1)

#Comperaction Operations
#-----------------------------  
arr==arr1
arr!=arr1
arr>arr1
arr<arr1
arr>=arr1
arr<=arr1

np.less_equal(arr,arr1)
np.greater_equal(arr,arr1)
np.less(arr,arr1)
np.greater(arr,arr1)
np.equal(arr,arr1)
np.not_equal(arr,arr1)

array([ True,  True,  True])

INDEXING / SLICING

In [90]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [94]:
arr[3]
arr[-1]
arr[1:4]
arr[1:]
arr[:3]
arr[::2]
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Sorting

In [98]:
ar=np.array([2,5,3,7,3,8,9,1])
ar.sort()
np.sort(ar)


array([1, 2, 3, 3, 5, 7, 8, 9])

array elements

In [111]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
a[0]
a[1]
a[2]
a[0][1]
a[2][2]
a[1:]
a[::-1]
a[::-1,::-1]


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
a.T
#row to columns ,column to rows it will change

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [120]:
a.min()
a.max()
a.sum()
a.argmin()
a.argmax()

np.int64(8)

## PANDAS

In [121]:
import pandas as pd

-->SERIES  
-->DATAFRAMES

SERIES  
-->1 DIM array

In [124]:
lst=[1,2,3,4,5]
s=pd.Series(lst)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

METHODS

In [126]:
s.shape

(5,)

In [127]:
s.size

5

In [128]:
s.dtype

dtype('int64')

In [132]:
v=s.astype(float)
v
v.dtype

dtype('float64')

In [ ]:
s.head(3) 
#top 3

0    1
1    2
2    3
dtype: int64

In [ ]:
s.tail(2)
#bottom 2

3    4
4    5
dtype: int64

In [150]:
#we can chainge indexing using index
f=pd.Series([1,2,3,4,5])
f.index=['Mango','Orange','Grapes','Banana','Apple']
f



Mango     1
Orange    2
Grapes    3
Banana    4
Apple     5
dtype: int64

In [151]:
#we can create name
s.name='Fruits'
s

0    1
1    2
2    3
3    4
4    5
Name: Fruits, dtype: int64

Static methods

In [161]:
p=pd.Series([1,2,3,4,3,5,5])
p.sum()
p.max()
p.min()
p.mean()
p.median()
p.mode()
p.std()
p.var()
p.count()

np.int64(7)

In [168]:
#value related methods
p.unique()
p.nunique()
p.value_counts()
p.duplicated()
p.sort_values()
p.sort_index()

0    1
1    2
2    3
3    4
4    3
5    5
6    5
dtype: int64